---
name: AtulJainPythonWorkflowVARIABLES
on: 
 workflow_dispatch:
 push:
env:
 PYTHON_VERSION: 3.9
 RUNNER_NAME: ubuntu-latest
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: clone the reop
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
         python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Dependencies
        run: |
         pip install --upgrade pip
         pip install -r requirements.txt
         echo  ${{ env.RUNNER_NAME }}
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: clone the reop
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
         python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Dependencies
        run: |
         pip install --upgrade pip
         pip install -r requirements.txt
